### ISSUE TITLE
All texture files are 1kb in size, those same files are much larger when searching for the individual model

### ISSUE THREAD

**Issue by wirelessdreamer** [makehumancommunity/communityassets#1]
The batch process that is creating or updating this git repo is not properly including textures. When I check out this repo and manually download textures the cloths work, but 90% of the textures distributed with this repo and currently broken, and need to be manually downloaded.

**Comment by joepal1976** [comment]
This is because you haven't enabled LFS. See https://git-lfs.github.com/

But that LFS is required should be mentioned in the README for the repo.

**Comment by wirelessdreamer** [comment]
Thanks that resolved my issue. I just created a pull request with an updated readme.

**Comment by joepal1976** [comment]
Closing issue as I merged the pull request with updated readme.
